version: 2

jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Test
          command: npm test
      - save_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  deploy:
    docker:
      - image: ruanzx/aws:alpine
    steps:
      - checkout
      - run:
          name: Setup environment
          command: eb use $ENVIRONMENT_NAME
      - run:
          name: Deploy
          command: eb deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
