version: 2

defaults: &defaults
  docker:
    - image: ruanzx/aws:alpine

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Test
          command: npm test
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Deploy
          command: echo "TODO"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy